# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi/openapi.yml:
  info-license:
    - '#/info'
  no-server-example.com:
    - '#/servers/0/url'
  no-server-localhost:
    - '#/servers/0/url'
openapi/paths/admin/login.yml:
  security-defined:
    - '#/post'
openapi/paths/admin/refresh.yml:
  security-defined:
    - '#/post'