services:
  api:
    container_name: api
    build:
      target: base
      context: .
      dockerfile: docker/go/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./src:/go/src/
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DBMS=${DBMS}
  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3334:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: