services:
  api:
    container_name: api
    build:
      target: base
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./src:/go/src/
    ports:
      - 8080:8080