openapi: 3.0.0
info:
  title: momonga blog API
  version: 1.0.0
  description: momonga blog API
servers:
  - url: https://hogehogehogedummy.com
    description: Production server
  - url: http://localhost:8080
    description: Local server
paths:
  # admin
  /login:
    $ref: paths/admin/login.yml
  /logout:
    $ref: paths/admin/logout.yml
  /admin/blog:
    $ref: paths/admin/blog.yml

  # public
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT