openapi: 3.0.0
info:
  title: momonga blog API
  version: 1.0.0
  description: momonga blog API
servers:
  - url: http://localhost:8080
    description: Local server
  - url: https://hogehogehogedummy.com
    description: Production server
paths:
  # admin
  /api/login:
    $ref: paths/admin/login.yml
  /api/logout:
    $ref: paths/admin/logout.yml
  /api/refresh:
    $ref: paths/admin/refresh.yml
  /api/admin/blog:
    $ref: paths/admin/blog.yml
  /api/admin/blog/{uuid}:
    $ref: paths/admin/blog_id.yml
  /api/admin/tags:
    $ref: paths/admin/tags.yml
  /api/admin/image/upload:
    $ref: paths/admin/image_upload.yml

  # public
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT